/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * My awesome API
 * My awesome API created with ZenStack
 * OpenAPI spec version: 0.5.0
 */
export type GroupByPost200 = {
  /** The Prisma response data serialized with superjson */
  data: PostGroupByOutputType[];
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type GroupByPostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostGroupByArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type AggregatePost200 = {
  /** The Prisma response data serialized with superjson */
  data: AggregatePost;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type AggregatePostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostAggregateArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

/**
 * The Prisma response data serialized with superjson
 */
export type CountPost200Data = number | PostCountAggregateOutputType;

export type CountPost200 = {
  /** The Prisma response data serialized with superjson */
  data: CountPost200Data;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type CountPostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostCountArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type DeleteManyPost200 = {
  /** The Prisma response data serialized with superjson */
  data: BatchPayload;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type DeleteManyPostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostDeleteManyArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type DeletePost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type DeletePostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostDeleteUniqueArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type UpsertPost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type UpdateManyPost200 = {
  /** The Prisma response data serialized with superjson */
  data: BatchPayload;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type UpdatePost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindManyPost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post[];
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindManyPostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostFindManyArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type FindFirstPost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindFirstPostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostFindFirstArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type FindUniquePost200 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindUniquePostParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: PostFindUniqueArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type CreatePost201 = {
  /** The Prisma response data serialized with superjson */
  data: Post;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type GroupByUser200 = {
  /** The Prisma response data serialized with superjson */
  data: UserGroupByOutputType[];
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type GroupByUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserGroupByArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type AggregateUser200 = {
  /** The Prisma response data serialized with superjson */
  data: AggregateUser;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type AggregateUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserAggregateArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

/**
 * The Prisma response data serialized with superjson
 */
export type CountUser200Data = number | UserCountAggregateOutputType;

export type CountUser200 = {
  /** The Prisma response data serialized with superjson */
  data: CountUser200Data;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type CountUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserCountArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type DeleteManyUser200 = {
  /** The Prisma response data serialized with superjson */
  data: BatchPayload;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type DeleteManyUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserDeleteManyArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type DeleteUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type DeleteUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserDeleteUniqueArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type UpsertUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type UpdateManyUser200 = {
  /** The Prisma response data serialized with superjson */
  data: BatchPayload;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type UpdateUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindManyUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User[];
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindManyUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserFindManyArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type FindFirstUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindFirstUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserFindFirstArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type FindUniqueUser200 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type FindUniqueUserParams = {
  /**
   * Superjson-serialized Prisma query object
   */
  q: UserFindUniqueArgs;
  /**
   * Superjson serialization metadata for parameter "q"
   */
  meta?: {};
};

export type CreateUser201 = {
  /** The Prisma response data serialized with superjson */
  data: User;
  /** The superjson serialization metadata for the "data" field */
  meta?: _Meta;
};

export type _PostGroupByArgsCount = boolean | PostCountAggregateInput;

export interface PostGroupByArgs {
  _avg?: PostAvgAggregateInput;
  _count?: _PostGroupByArgsCount;
  _max?: PostMaxAggregateInput;
  _min?: PostMinAggregateInput;
  _sum?: PostSumAggregateInput;
  by?: PostScalarFieldEnum;
  having?: PostScalarWhereWithAggregatesInput;
  meta?: _Meta;
  orderBy?: PostOrderByWithRelationInput;
  skip?: number;
  take?: number;
  where?: PostWhereInput;
}

export type _PostAggregateArgsCount = boolean | PostCountAggregateInput;

export interface PostAggregateArgs {
  _avg?: PostAvgAggregateInput;
  _count?: _PostAggregateArgsCount;
  _max?: PostMaxAggregateInput;
  _min?: PostMinAggregateInput;
  _sum?: PostSumAggregateInput;
  cursor?: PostWhereUniqueInput;
  meta?: _Meta;
  orderBy?: PostOrderByWithRelationInput;
  skip?: number;
  take?: number;
  where?: PostWhereInput;
}

export interface PostCountArgs {
  meta?: _Meta;
  select?: PostSelect;
  where?: PostWhereInput;
}

export interface PostDeleteManyArgs {
  meta?: _Meta;
  where?: PostWhereInput;
}

export interface PostDeleteUniqueArgs {
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  where: PostWhereUniqueInput;
}

export interface PostUpsertArgs {
  create: PostCreateInput;
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  update: PostUpdateInput;
  where: PostWhereUniqueInput;
}

export interface PostUpdateManyArgs {
  data: PostUpdateManyMutationInput;
  meta?: _Meta;
  where?: PostWhereInput;
}

export interface PostUpdateArgs {
  data: PostUpdateInput;
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  where: PostWhereUniqueInput;
}

export interface PostFindManyArgs {
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  where?: PostWhereInput;
}

export interface PostFindFirstArgs {
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  where?: PostWhereInput;
}

export interface PostFindUniqueArgs {
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
  where: PostWhereUniqueInput;
}

export interface PostCreateArgs {
  data: PostCreateInput;
  include?: PostInclude;
  meta?: _Meta;
  select?: PostSelect;
}

export type _UserGroupByArgsCount = boolean | UserCountAggregateInput;

export interface UserGroupByArgs {
  _avg?: UserAvgAggregateInput;
  _count?: _UserGroupByArgsCount;
  _max?: UserMaxAggregateInput;
  _min?: UserMinAggregateInput;
  _sum?: UserSumAggregateInput;
  by?: UserScalarFieldEnum;
  having?: UserScalarWhereWithAggregatesInput;
  meta?: _Meta;
  orderBy?: UserOrderByWithRelationInput;
  skip?: number;
  take?: number;
  where?: UserWhereInput;
}

export type _UserAggregateArgsCount = boolean | UserCountAggregateInput;

export interface UserUpsertArgs {
  create: UserCreateInput;
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  update: UserUpdateInput;
  where: UserWhereUniqueInput;
}

export interface UserUpdateArgs {
  data: UserUpdateInput;
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  where: UserWhereUniqueInput;
}

export interface UserFindManyArgs {
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  where?: UserWhereInput;
}

export interface UserFindFirstArgs {
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  where?: UserWhereInput;
}

export interface UserFindUniqueArgs {
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  where: UserWhereUniqueInput;
}

export interface UserCreateArgs {
  data: UserCreateInput;
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
}

export interface BatchPayload {
  count?: number;
}

/**
 * Zod validation errors if the error is due to data validation failure
 */
export type _ErrorErrorZodErrors = { [key: string]: any };

export type _ErrorError = {
  /** Prisma error code. Only available when "prisma" field is true. */
  code?: string;
  /** Error message */
  message: string;
  /** Indicates if the error occurred during a Prisma call */
  prisma?: boolean;
  /** Detailed error reason */
  reason?: string;
  /** Indicates if the error was due to rejection by a policy */
  rejectedByPolicy?: boolean;
  /** Zod validation errors if the error is due to data validation failure */
  zodErrors?: _ErrorErrorZodErrors;
  [key: string]: any;
};

export interface _Error {
  error: _ErrorError;
}

/**
 * Serialization metadata
 */
export type _MetaMetaSerialization = {};

/**
 * Meta information about the request or response
 */
export type _MetaMeta = {
  /** Serialization metadata */
  serialization?: _MetaMetaSerialization;
  [key: string]: any;
};

export interface _Meta {
  /** Meta information about the request or response */
  meta?: _MetaMeta;
}

export interface UserAggregateArgs {
  _avg?: UserAvgAggregateInput;
  _count?: _UserAggregateArgsCount;
  _max?: UserMaxAggregateInput;
  _min?: UserMinAggregateInput;
  _sum?: UserSumAggregateInput;
  cursor?: UserWhereUniqueInput;
  meta?: _Meta;
  orderBy?: UserOrderByWithRelationInput;
  skip?: number;
  take?: number;
  where?: UserWhereInput;
}

export interface UserCountArgs {
  meta?: _Meta;
  select?: UserSelect;
  where?: UserWhereInput;
}

export interface UserDeleteManyArgs {
  meta?: _Meta;
  where?: UserWhereInput;
}

export interface UserDeleteUniqueArgs {
  include?: UserInclude;
  meta?: _Meta;
  select?: UserSelect;
  where: UserWhereUniqueInput;
}

export interface UserUpdateManyArgs {
  data: UserUpdateManyMutationInput;
  meta?: _Meta;
  where?: UserWhereInput;
}

export type PostMaxAggregateOutputTypeViewCount = null | number;

export type PostMaxAggregateOutputTypeUpdatedAt = null | string;

export type PostMaxAggregateOutputTypeTitle = null | string;

export type PostMaxAggregateOutputTypePublished = null | boolean;

export type PostMaxAggregateOutputTypeId = null | number;

export type PostMaxAggregateOutputTypeCreatedAt = null | string;

export type PostMaxAggregateOutputTypeContent = null | string;

export type PostMaxAggregateOutputTypeAuthorId = null | number;

export interface PostMaxAggregateOutputType {
  authorId?: PostMaxAggregateOutputTypeAuthorId;
  content?: PostMaxAggregateOutputTypeContent;
  createdAt?: PostMaxAggregateOutputTypeCreatedAt;
  id?: PostMaxAggregateOutputTypeId;
  published?: PostMaxAggregateOutputTypePublished;
  title?: PostMaxAggregateOutputTypeTitle;
  updatedAt?: PostMaxAggregateOutputTypeUpdatedAt;
  viewCount?: PostMaxAggregateOutputTypeViewCount;
}

export type PostMinAggregateOutputTypeViewCount = null | number;

export type PostMinAggregateOutputTypeUpdatedAt = null | string;

export type PostMinAggregateOutputTypeTitle = null | string;

export type PostMinAggregateOutputTypePublished = null | boolean;

export type PostMinAggregateOutputTypeId = null | number;

export type PostMinAggregateOutputTypeCreatedAt = null | string;

export type PostMinAggregateOutputTypeContent = null | string;

export type PostMinAggregateOutputTypeAuthorId = null | number;

export interface PostMinAggregateOutputType {
  authorId?: PostMinAggregateOutputTypeAuthorId;
  content?: PostMinAggregateOutputTypeContent;
  createdAt?: PostMinAggregateOutputTypeCreatedAt;
  id?: PostMinAggregateOutputTypeId;
  published?: PostMinAggregateOutputTypePublished;
  title?: PostMinAggregateOutputTypeTitle;
  updatedAt?: PostMinAggregateOutputTypeUpdatedAt;
  viewCount?: PostMinAggregateOutputTypeViewCount;
}

export type PostSumAggregateOutputTypeViewCount = null | number;

export type PostSumAggregateOutputTypeId = null | number;

export type PostSumAggregateOutputTypeAuthorId = null | number;

export interface PostSumAggregateOutputType {
  authorId?: PostSumAggregateOutputTypeAuthorId;
  id?: PostSumAggregateOutputTypeId;
  viewCount?: PostSumAggregateOutputTypeViewCount;
}

export type PostAvgAggregateOutputTypeViewCount = null | number;

export type PostAvgAggregateOutputTypeId = null | number;

export type PostAvgAggregateOutputTypeAuthorId = null | number;

export interface PostAvgAggregateOutputType {
  authorId?: PostAvgAggregateOutputTypeAuthorId;
  id?: PostAvgAggregateOutputTypeId;
  viewCount?: PostAvgAggregateOutputTypeViewCount;
}

export interface PostCountAggregateOutputType {
  _all: number;
  authorId: number;
  content: number;
  createdAt: number;
  id: number;
  published: number;
  title: number;
  updatedAt: number;
  viewCount: number;
}

export type UserMaxAggregateOutputTypeName = null | string;

export type UserMaxAggregateOutputTypeId = null | number;

export type UserMaxAggregateOutputTypeEmail = null | string;

export interface UserMaxAggregateOutputType {
  email?: UserMaxAggregateOutputTypeEmail;
  id?: UserMaxAggregateOutputTypeId;
  name?: UserMaxAggregateOutputTypeName;
}

export type UserMinAggregateOutputTypeName = null | string;

export type UserMinAggregateOutputTypeId = null | number;

export type UserMinAggregateOutputTypeEmail = null | string;

export interface UserMinAggregateOutputType {
  email?: UserMinAggregateOutputTypeEmail;
  id?: UserMinAggregateOutputTypeId;
  name?: UserMinAggregateOutputTypeName;
}

export type UserSumAggregateOutputTypeId = null | number;

export interface UserSumAggregateOutputType {
  id?: UserSumAggregateOutputTypeId;
}

export type UserAvgAggregateOutputTypeId = null | number;

export interface UserAvgAggregateOutputType {
  id?: UserAvgAggregateOutputTypeId;
}

export interface UserCountAggregateOutputType {
  _all: number;
  email: number;
  id: number;
  name: number;
}

export type PostGroupByOutputTypeContent = null | string;

export type PostGroupByOutputTypeAuthorId = null | number;

export type _PostGroupByOutputTypeSum = null | PostSumAggregateOutputType;

export type _PostGroupByOutputTypeMin = null | PostMinAggregateOutputType;

export type _PostGroupByOutputTypeMax = null | PostMaxAggregateOutputType;

export type _PostGroupByOutputTypeCount = null | PostCountAggregateOutputType;

export type _PostGroupByOutputTypeAvg = null | PostAvgAggregateOutputType;

export interface PostGroupByOutputType {
  _avg?: _PostGroupByOutputTypeAvg;
  _count?: _PostGroupByOutputTypeCount;
  _max?: _PostGroupByOutputTypeMax;
  _min?: _PostGroupByOutputTypeMin;
  _sum?: _PostGroupByOutputTypeSum;
  authorId?: PostGroupByOutputTypeAuthorId;
  content?: PostGroupByOutputTypeContent;
  createdAt: string;
  id: number;
  published: boolean;
  title: string;
  updatedAt: string;
  viewCount: number;
}

export type _AggregatePostSum = null | PostSumAggregateOutputType;

export type _AggregatePostMin = null | PostMinAggregateOutputType;

export type _AggregatePostMax = null | PostMaxAggregateOutputType;

export type _AggregatePostCount = null | PostCountAggregateOutputType;

export type _AggregatePostAvg = null | PostAvgAggregateOutputType;

export interface AggregatePost {
  _avg?: _AggregatePostAvg;
  _count?: _AggregatePostCount;
  _max?: _AggregatePostMax;
  _min?: _AggregatePostMin;
  _sum?: _AggregatePostSum;
}

export type _UserGroupByOutputTypeSum = null | UserSumAggregateOutputType;

export type _UserGroupByOutputTypeMin = null | UserMinAggregateOutputType;

export type _UserGroupByOutputTypeMax = null | UserMaxAggregateOutputType;

export type _UserGroupByOutputTypeCount = null | UserCountAggregateOutputType;

export type _UserGroupByOutputTypeAvg = null | UserAvgAggregateOutputType;

export interface UserGroupByOutputType {
  _avg?: _UserGroupByOutputTypeAvg;
  _count?: _UserGroupByOutputTypeCount;
  _max?: _UserGroupByOutputTypeMax;
  _min?: _UserGroupByOutputTypeMin;
  _sum?: _UserGroupByOutputTypeSum;
  email: string;
  id: number;
  name: string;
}

export type _AggregateUserSum = null | UserSumAggregateOutputType;

export type _AggregateUserMin = null | UserMinAggregateOutputType;

export type _AggregateUserMax = null | UserMaxAggregateOutputType;

export type _AggregateUserCount = null | UserCountAggregateOutputType;

export type _AggregateUserAvg = null | UserAvgAggregateOutputType;

export interface AggregateUser {
  _avg?: _AggregateUserAvg;
  _count?: _AggregateUserCount;
  _max?: _AggregateUserMax;
  _min?: _AggregateUserMin;
  _sum?: _AggregateUserSum;
}

export interface PostMaxAggregateInput {
  authorId?: boolean;
  content?: boolean;
  createdAt?: boolean;
  id?: boolean;
  published?: boolean;
  title?: boolean;
  updatedAt?: boolean;
  viewCount?: boolean;
}

export interface PostMinAggregateInput {
  authorId?: boolean;
  content?: boolean;
  createdAt?: boolean;
  id?: boolean;
  published?: boolean;
  title?: boolean;
  updatedAt?: boolean;
  viewCount?: boolean;
}

export interface PostSumAggregateInput {
  authorId?: boolean;
  id?: boolean;
  viewCount?: boolean;
}

export interface PostAvgAggregateInput {
  authorId?: boolean;
  id?: boolean;
  viewCount?: boolean;
}

export interface PostCountAggregateInput {
  _all?: boolean;
  authorId?: boolean;
  content?: boolean;
  createdAt?: boolean;
  id?: boolean;
  published?: boolean;
  title?: boolean;
  updatedAt?: boolean;
  viewCount?: boolean;
}

export interface UserMaxAggregateInput {
  email?: boolean;
  id?: boolean;
  name?: boolean;
}

export interface UserMinAggregateInput {
  email?: boolean;
  id?: boolean;
  name?: boolean;
}

export interface UserSumAggregateInput {
  id?: boolean;
}

export interface UserAvgAggregateInput {
  id?: boolean;
}

export interface UserCountAggregateInput {
  _all?: boolean;
  email?: boolean;
  id?: boolean;
  name?: boolean;
}

export type PostSelectAuthor = boolean | UserArgs;

export interface PostSelect {
  author?: PostSelectAuthor;
  authorId?: boolean;
  content?: boolean;
  createdAt?: boolean;
  id?: boolean;
  published?: boolean;
  title?: boolean;
  updatedAt?: boolean;
  viewCount?: boolean;
}

export type UserSelectPosts = boolean | PostFindManyArgs;

export interface UserCountOutputTypeSelect {
  posts?: boolean;
}

export interface UserCountOutputTypeArgs {
  select?: UserCountOutputTypeSelect;
}

export type _UserSelectCount = boolean | UserCountOutputTypeArgs;

export interface UserSelect {
  _count?: _UserSelectCount;
  email?: boolean;
  id?: boolean;
  name?: boolean;
  posts?: UserSelectPosts;
}

export type UserIncludePosts = boolean | PostFindManyArgs;

export type _UserIncludeCount = boolean | UserCountOutputTypeArgs;

export interface UserInclude {
  _count?: _UserIncludeCount;
  posts?: UserIncludePosts;
}

export interface UserArgs {
  include?: UserInclude;
  select?: UserSelect;
}

export type PostIncludeAuthor = boolean | UserArgs;

export interface PostInclude {
  author?: PostIncludeAuthor;
}

export type PostUncheckedUpdateManyWithoutPostsInputViewCount = number | IntFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputUpdatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputTitle = string | StringFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputPublished = boolean | BoolFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputId = number | IntFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputCreatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUncheckedUpdateManyWithoutPostsInputContent = string | NullableStringFieldUpdateOperationsInput | null;

export interface PostUncheckedUpdateManyWithoutPostsInput {
  content?: PostUncheckedUpdateManyWithoutPostsInputContent;
  createdAt?: PostUncheckedUpdateManyWithoutPostsInputCreatedAt;
  id?: PostUncheckedUpdateManyWithoutPostsInputId;
  published?: PostUncheckedUpdateManyWithoutPostsInputPublished;
  title?: PostUncheckedUpdateManyWithoutPostsInputTitle;
  updatedAt?: PostUncheckedUpdateManyWithoutPostsInputUpdatedAt;
  viewCount?: PostUncheckedUpdateManyWithoutPostsInputViewCount;
}

export type PostUncheckedUpdateWithoutAuthorInputViewCount = number | IntFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputUpdatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputTitle = string | StringFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputPublished = boolean | BoolFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputId = number | IntFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputCreatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUncheckedUpdateWithoutAuthorInputContent = string | NullableStringFieldUpdateOperationsInput | null;

export interface PostUncheckedUpdateWithoutAuthorInput {
  content?: PostUncheckedUpdateWithoutAuthorInputContent;
  createdAt?: PostUncheckedUpdateWithoutAuthorInputCreatedAt;
  id?: PostUncheckedUpdateWithoutAuthorInputId;
  published?: PostUncheckedUpdateWithoutAuthorInputPublished;
  title?: PostUncheckedUpdateWithoutAuthorInputTitle;
  updatedAt?: PostUncheckedUpdateWithoutAuthorInputUpdatedAt;
  viewCount?: PostUncheckedUpdateWithoutAuthorInputViewCount;
}

export type PostUpdateWithoutAuthorInputViewCount = number | IntFieldUpdateOperationsInput;

export type PostUpdateWithoutAuthorInputUpdatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateWithoutAuthorInputTitle = string | StringFieldUpdateOperationsInput;

export type PostUpdateWithoutAuthorInputPublished = boolean | BoolFieldUpdateOperationsInput;

export type PostUpdateWithoutAuthorInputCreatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateWithoutAuthorInputContent = string | NullableStringFieldUpdateOperationsInput | null;

export interface PostUpdateWithoutAuthorInput {
  content?: PostUpdateWithoutAuthorInputContent;
  createdAt?: PostUpdateWithoutAuthorInputCreatedAt;
  published?: PostUpdateWithoutAuthorInputPublished;
  title?: PostUpdateWithoutAuthorInputTitle;
  updatedAt?: PostUpdateWithoutAuthorInputUpdatedAt;
  viewCount?: PostUpdateWithoutAuthorInputViewCount;
}

export type UserUncheckedUpdateWithoutPostsInputName = string | StringFieldUpdateOperationsInput;

export type UserUncheckedUpdateWithoutPostsInputId = number | IntFieldUpdateOperationsInput;

export type UserUncheckedUpdateWithoutPostsInputEmail = string | StringFieldUpdateOperationsInput;

export interface UserUncheckedUpdateWithoutPostsInput {
  email?: UserUncheckedUpdateWithoutPostsInputEmail;
  id?: UserUncheckedUpdateWithoutPostsInputId;
  name?: UserUncheckedUpdateWithoutPostsInputName;
}

export type UserUpdateWithoutPostsInputName = string | StringFieldUpdateOperationsInput;

export type UserUpdateWithoutPostsInputEmail = string | StringFieldUpdateOperationsInput;

export interface UserUpdateWithoutPostsInput {
  email?: UserUpdateWithoutPostsInputEmail;
  name?: UserUpdateWithoutPostsInputName;
}

export type UserUpdateToOneWithWhereWithoutPostsInputData = UserUpdateWithoutPostsInput | UserUncheckedUpdateWithoutPostsInput;

export interface UserUpdateToOneWithWhereWithoutPostsInput {
  data: UserUpdateToOneWithWhereWithoutPostsInputData;
  where?: UserWhereInput;
}

export type UserUpsertWithoutPostsInputUpdate = UserUpdateWithoutPostsInput | UserUncheckedUpdateWithoutPostsInput;

export interface UserUpsertWithoutPostsInput {
  create: UserUpsertWithoutPostsInputCreate;
  update: UserUpsertWithoutPostsInputUpdate;
  where?: UserWhereInput;
}

export interface UserCreateOrConnectWithoutPostsInput {
  create: UserCreateOrConnectWithoutPostsInputCreate;
  where: UserWhereUniqueInput;
}

export interface UserUncheckedCreateWithoutPostsInput {
  email: string;
  id?: number;
  name: string;
}

export interface UserCreateWithoutPostsInput {
  email: string;
  name: string;
}

export type UserUpsertWithoutPostsInputCreate = UserCreateWithoutPostsInput | UserUncheckedCreateWithoutPostsInput;

export type UserCreateOrConnectWithoutPostsInputCreate = UserCreateWithoutPostsInput | UserUncheckedCreateWithoutPostsInput;

export type PostScalarWhereInputViewCount = IntFilter | number;

export type PostScalarWhereInputUpdatedAt = DateTimeFilter | string;

export type PostScalarWhereInputTitle = StringFilter | string;

export type PostScalarWhereInputPublished = BoolFilter | boolean;

export type PostScalarWhereInputNOT = PostScalarWhereInput | PostScalarWhereInput[];

export type PostScalarWhereInputId = IntFilter | number;

export type PostScalarWhereInputCreatedAt = DateTimeFilter | string;

export type PostScalarWhereInputContent = StringNullableFilter | string | null;

export type PostScalarWhereInputAuthorId = IntNullableFilter | number | null;

export type PostScalarWhereInputAND = PostScalarWhereInput | PostScalarWhereInput[];

export interface PostScalarWhereInput {
  AND?: PostScalarWhereInputAND;
  authorId?: PostScalarWhereInputAuthorId;
  content?: PostScalarWhereInputContent;
  createdAt?: PostScalarWhereInputCreatedAt;
  id?: PostScalarWhereInputId;
  NOT?: PostScalarWhereInputNOT;
  OR?: PostScalarWhereInput[];
  published?: PostScalarWhereInputPublished;
  title?: PostScalarWhereInputTitle;
  updatedAt?: PostScalarWhereInputUpdatedAt;
  viewCount?: PostScalarWhereInputViewCount;
}

export type PostUpdateManyWithWhereWithoutAuthorInputData = PostUpdateManyMutationInput | PostUncheckedUpdateManyWithoutPostsInput;

export interface PostUpdateManyWithWhereWithoutAuthorInput {
  data: PostUpdateManyWithWhereWithoutAuthorInputData;
  where: PostScalarWhereInput;
}

export type PostUpdateWithWhereUniqueWithoutAuthorInputData = PostUpdateWithoutAuthorInput | PostUncheckedUpdateWithoutAuthorInput;

export interface PostUpdateWithWhereUniqueWithoutAuthorInput {
  data: PostUpdateWithWhereUniqueWithoutAuthorInputData;
  where: PostWhereUniqueInput;
}

export type PostUpsertWithWhereUniqueWithoutAuthorInputUpdate = PostUpdateWithoutAuthorInput | PostUncheckedUpdateWithoutAuthorInput;

export interface PostUncheckedCreateWithoutAuthorInput {
  content?: PostUncheckedCreateWithoutAuthorInputContent;
  createdAt?: string;
  id?: number;
  published?: boolean;
  title: string;
  updatedAt?: string;
  viewCount?: number;
}

export type PostUpsertWithWhereUniqueWithoutAuthorInputCreate = PostCreateWithoutAuthorInput | PostUncheckedCreateWithoutAuthorInput;

export interface PostUpsertWithWhereUniqueWithoutAuthorInput {
  create: PostUpsertWithWhereUniqueWithoutAuthorInputCreate;
  update: PostUpsertWithWhereUniqueWithoutAuthorInputUpdate;
  where: PostWhereUniqueInput;
}

export type PostCreateOrConnectWithoutAuthorInputCreate = PostCreateWithoutAuthorInput | PostUncheckedCreateWithoutAuthorInput;

export interface PostCreateOrConnectWithoutAuthorInput {
  create: PostCreateOrConnectWithoutAuthorInputCreate;
  where: PostWhereUniqueInput;
}

export type PostUncheckedCreateWithoutAuthorInputContent = null | string;

export type PostCreateWithoutAuthorInputContent = null | string;

export interface PostCreateWithoutAuthorInput {
  content?: PostCreateWithoutAuthorInputContent;
  createdAt?: string;
  published?: boolean;
  title: string;
  updatedAt?: string;
  viewCount?: number;
}

export type NestedFloatNullableFilterNotIn = number[] | number | null;

export type NestedFloatNullableFilterNot = number | NestedFloatNullableFilter | null;

export type NestedFloatNullableFilterIn = number[] | number | null;

export type NestedFloatNullableFilterEquals = null | number;

export interface NestedFloatNullableFilter {
  equals?: NestedFloatNullableFilterEquals;
  gt?: number;
  gte?: number;
  in?: NestedFloatNullableFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedFloatNullableFilterNot;
  notIn?: NestedFloatNullableFilterNotIn;
}

export type NestedIntNullableWithAggregatesFilterNotIn = number[] | number | null;

export type NestedIntNullableWithAggregatesFilterNot = number | NestedIntNullableWithAggregatesFilter | null;

export type NestedIntNullableWithAggregatesFilterIn = number[] | number | null;

export type NestedIntNullableWithAggregatesFilterEquals = null | number;

export interface NestedIntNullableWithAggregatesFilter {
  _avg?: NestedFloatNullableFilter;
  _count?: NestedIntNullableFilter;
  _max?: NestedIntNullableFilter;
  _min?: NestedIntNullableFilter;
  _sum?: NestedIntNullableFilter;
  equals?: NestedIntNullableWithAggregatesFilterEquals;
  gt?: number;
  gte?: number;
  in?: NestedIntNullableWithAggregatesFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedIntNullableWithAggregatesFilterNot;
  notIn?: NestedIntNullableWithAggregatesFilterNotIn;
}

export type NestedBoolWithAggregatesFilterNot = boolean | NestedBoolWithAggregatesFilter;

export interface NestedBoolWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedBoolFilter;
  _min?: NestedBoolFilter;
  equals?: boolean;
  not?: NestedBoolWithAggregatesFilterNot;
}

export type NestedStringNullableWithAggregatesFilterNotIn = string[] | string | null;

export type NestedStringNullableWithAggregatesFilterNot = string | NestedStringNullableWithAggregatesFilter | null;

export type NestedStringNullableWithAggregatesFilterIn = string[] | string | null;

export type NestedStringNullableWithAggregatesFilterEquals = null | string;

export interface NestedStringNullableWithAggregatesFilter {
  _count?: NestedIntNullableFilter;
  _max?: NestedStringNullableFilter;
  _min?: NestedStringNullableFilter;
  contains?: string;
  endsWith?: string;
  equals?: NestedStringNullableWithAggregatesFilterEquals;
  gt?: string;
  gte?: string;
  in?: NestedStringNullableWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedStringNullableWithAggregatesFilterNot;
  notIn?: NestedStringNullableWithAggregatesFilterNotIn;
  startsWith?: string;
}

export type NestedDateTimeWithAggregatesFilterNotIn = string[] | string;

export type NestedDateTimeWithAggregatesFilterNot = string | NestedDateTimeWithAggregatesFilter;

export type NestedDateTimeWithAggregatesFilterIn = string[] | string;

export type NestedIntNullableFilterNotIn = number[] | number | null;

export type NestedIntNullableFilterNot = number | NestedIntNullableFilter | null;

export type NestedIntNullableFilterIn = number[] | number | null;

export type NestedIntNullableFilterEquals = null | number;

export interface NestedIntNullableFilter {
  equals?: NestedIntNullableFilterEquals;
  gt?: number;
  gte?: number;
  in?: NestedIntNullableFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedIntNullableFilterNot;
  notIn?: NestedIntNullableFilterNotIn;
}

export type NestedBoolFilterNot = boolean | NestedBoolFilter;

export interface NestedBoolFilter {
  equals?: boolean;
  not?: NestedBoolFilterNot;
}

export type NestedStringNullableFilterNotIn = string[] | string | null;

export type NestedStringNullableFilterNot = string | NestedStringNullableFilter | null;

export type NestedStringNullableFilterIn = string[] | string | null;

export type NestedStringNullableFilterEquals = null | string;

export interface NestedStringNullableFilter {
  contains?: string;
  endsWith?: string;
  equals?: NestedStringNullableFilterEquals;
  gt?: string;
  gte?: string;
  in?: NestedStringNullableFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedStringNullableFilterNot;
  notIn?: NestedStringNullableFilterNotIn;
  startsWith?: string;
}

export type NestedDateTimeFilterNotIn = string[] | string;

export type NestedDateTimeFilterNot = string | NestedDateTimeFilter;

export type NestedDateTimeFilterIn = string[] | string;

export interface NestedDateTimeFilter {
  equals?: string;
  gt?: string;
  gte?: string;
  in?: NestedDateTimeFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedDateTimeFilterNot;
  notIn?: NestedDateTimeFilterNotIn;
}

export interface NestedDateTimeWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedDateTimeFilter;
  _min?: NestedDateTimeFilter;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: NestedDateTimeWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedDateTimeWithAggregatesFilterNot;
  notIn?: NestedDateTimeWithAggregatesFilterNotIn;
}

export type NestedStringWithAggregatesFilterNotIn = string[] | string;

export type NestedStringWithAggregatesFilterNot = string | NestedStringWithAggregatesFilter;

export type NestedStringWithAggregatesFilterIn = string[] | string;

export interface NestedStringWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedStringFilter;
  _min?: NestedStringFilter;
  contains?: string;
  endsWith?: string;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: NestedStringWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedStringWithAggregatesFilterNot;
  notIn?: NestedStringWithAggregatesFilterNotIn;
  startsWith?: string;
}

export type NestedFloatFilterNotIn = number[] | number;

export type NestedFloatFilterNot = number | NestedFloatFilter;

export type NestedFloatFilterIn = number[] | number;

export interface NestedFloatFilter {
  equals?: number;
  gt?: number;
  gte?: number;
  in?: NestedFloatFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedFloatFilterNot;
  notIn?: NestedFloatFilterNotIn;
}

export type NestedIntWithAggregatesFilterNotIn = number[] | number;

export type NestedIntWithAggregatesFilterNot = number | NestedIntWithAggregatesFilter;

export type NestedIntWithAggregatesFilterIn = number[] | number;

export interface NestedIntWithAggregatesFilter {
  _avg?: NestedFloatFilter;
  _count?: NestedIntFilter;
  _max?: NestedIntFilter;
  _min?: NestedIntFilter;
  _sum?: NestedIntFilter;
  equals?: number;
  gt?: number;
  gte?: number;
  in?: NestedIntWithAggregatesFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedIntWithAggregatesFilterNot;
  notIn?: NestedIntWithAggregatesFilterNotIn;
}

export type NestedStringFilterNotIn = string[] | string;

export type NestedStringFilterNot = string | NestedStringFilter;

export type NestedStringFilterIn = string[] | string;

export interface NestedStringFilter {
  contains?: string;
  endsWith?: string;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: NestedStringFilterIn;
  lt?: string;
  lte?: string;
  not?: NestedStringFilterNot;
  notIn?: NestedStringFilterNotIn;
  startsWith?: string;
}

export type NestedIntFilterNotIn = number[] | number;

export type NestedIntFilterNot = number | NestedIntFilter;

export type NestedIntFilterIn = number[] | number;

export interface NestedIntFilter {
  equals?: number;
  gt?: number;
  gte?: number;
  in?: NestedIntFilterIn;
  lt?: number;
  lte?: number;
  not?: NestedIntFilterNot;
  notIn?: NestedIntFilterNotIn;
}

export type UserUpdateOneWithoutPostsNestedInputUpdate =
  | UserUpdateToOneWithWhereWithoutPostsInput
  | UserUpdateWithoutPostsInput
  | UserUncheckedUpdateWithoutPostsInput;

export type UserUpdateOneWithoutPostsNestedInputDisconnect = boolean | UserWhereInput;

export type UserUpdateOneWithoutPostsNestedInputDelete = boolean | UserWhereInput;

export type UserUpdateOneWithoutPostsNestedInputCreate = UserCreateWithoutPostsInput | UserUncheckedCreateWithoutPostsInput;

export interface UserUpdateOneWithoutPostsNestedInput {
  connect?: UserWhereUniqueInput;
  connectOrCreate?: UserCreateOrConnectWithoutPostsInput;
  create?: UserUpdateOneWithoutPostsNestedInputCreate;
  delete?: UserUpdateOneWithoutPostsNestedInputDelete;
  disconnect?: UserUpdateOneWithoutPostsNestedInputDisconnect;
  update?: UserUpdateOneWithoutPostsNestedInputUpdate;
  upsert?: UserUpsertWithoutPostsInput;
}

export interface BoolFieldUpdateOperationsInput {
  set?: boolean;
}

export type NullableStringFieldUpdateOperationsInputSet = null | string;

export interface NullableStringFieldUpdateOperationsInput {
  set?: NullableStringFieldUpdateOperationsInputSet;
}

export interface DateTimeFieldUpdateOperationsInput {
  set?: string;
}

export type UserCreateNestedOneWithoutPostsInputCreate = UserCreateWithoutPostsInput | UserUncheckedCreateWithoutPostsInput;

export interface UserCreateNestedOneWithoutPostsInput {
  connect?: UserWhereUniqueInput;
  connectOrCreate?: UserCreateOrConnectWithoutPostsInput;
  create?: UserCreateNestedOneWithoutPostsInputCreate;
}

export interface IntFieldUpdateOperationsInput {
  decrement?: number;
  divide?: number;
  increment?: number;
  multiply?: number;
  set?: number;
}

export type PostUpdateManyWithoutAuthorNestedInputUpsert =
  | PostUpsertWithWhereUniqueWithoutAuthorInput
  | PostUpsertWithWhereUniqueWithoutAuthorInput[];

export type PostUpdateManyWithoutAuthorNestedInputUpdateMany =
  | PostUpdateManyWithWhereWithoutAuthorInput
  | PostUpdateManyWithWhereWithoutAuthorInput[];

export type PostUpdateManyWithoutAuthorNestedInputUpdate =
  | PostUpdateWithWhereUniqueWithoutAuthorInput
  | PostUpdateWithWhereUniqueWithoutAuthorInput[];

export type PostUpdateManyWithoutAuthorNestedInputSet = PostWhereUniqueInput | PostWhereUniqueInput[];

export type PostUpdateManyWithoutAuthorNestedInputDisconnect = PostWhereUniqueInput | PostWhereUniqueInput[];

export type PostUpdateManyWithoutAuthorNestedInputDeleteMany = PostScalarWhereInput | PostScalarWhereInput[];

export type PostUpdateManyWithoutAuthorNestedInputDelete = PostWhereUniqueInput | PostWhereUniqueInput[];

export type PostUpdateManyWithoutAuthorNestedInputCreate =
  | PostCreateWithoutAuthorInput
  | PostCreateWithoutAuthorInput[]
  | PostUncheckedCreateWithoutAuthorInput
  | PostUncheckedCreateWithoutAuthorInput[];

export type PostUpdateManyWithoutAuthorNestedInputConnectOrCreate =
  | PostCreateOrConnectWithoutAuthorInput
  | PostCreateOrConnectWithoutAuthorInput[];

export type PostUpdateManyWithoutAuthorNestedInputConnect = PostWhereUniqueInput | PostWhereUniqueInput[];

export interface PostUpdateManyWithoutAuthorNestedInput {
  connect?: PostUpdateManyWithoutAuthorNestedInputConnect;
  connectOrCreate?: PostUpdateManyWithoutAuthorNestedInputConnectOrCreate;
  create?: PostUpdateManyWithoutAuthorNestedInputCreate;
  delete?: PostUpdateManyWithoutAuthorNestedInputDelete;
  deleteMany?: PostUpdateManyWithoutAuthorNestedInputDeleteMany;
  disconnect?: PostUpdateManyWithoutAuthorNestedInputDisconnect;
  set?: PostUpdateManyWithoutAuthorNestedInputSet;
  update?: PostUpdateManyWithoutAuthorNestedInputUpdate;
  updateMany?: PostUpdateManyWithoutAuthorNestedInputUpdateMany;
  upsert?: PostUpdateManyWithoutAuthorNestedInputUpsert;
}

export interface StringFieldUpdateOperationsInput {
  set?: string;
}

export type PostCreateNestedManyWithoutAuthorInputCreate =
  | PostCreateWithoutAuthorInput
  | PostCreateWithoutAuthorInput[]
  | PostUncheckedCreateWithoutAuthorInput
  | PostUncheckedCreateWithoutAuthorInput[];

export type PostCreateNestedManyWithoutAuthorInputConnectOrCreate =
  | PostCreateOrConnectWithoutAuthorInput
  | PostCreateOrConnectWithoutAuthorInput[];

export type PostCreateNestedManyWithoutAuthorInputConnect = PostWhereUniqueInput | PostWhereUniqueInput[];

export interface PostCreateNestedManyWithoutAuthorInput {
  connect?: PostCreateNestedManyWithoutAuthorInputConnect;
  connectOrCreate?: PostCreateNestedManyWithoutAuthorInputConnectOrCreate;
  create?: PostCreateNestedManyWithoutAuthorInputCreate;
}

export type IntNullableWithAggregatesFilterNotIn = number[] | number | null;

export type IntNullableWithAggregatesFilterNot = number | NestedIntNullableWithAggregatesFilter | null;

export type IntNullableWithAggregatesFilterIn = number[] | number | null;

export type IntNullableWithAggregatesFilterEquals = null | number;

export interface IntNullableWithAggregatesFilter {
  _avg?: NestedFloatNullableFilter;
  _count?: NestedIntNullableFilter;
  _max?: NestedIntNullableFilter;
  _min?: NestedIntNullableFilter;
  _sum?: NestedIntNullableFilter;
  equals?: IntNullableWithAggregatesFilterEquals;
  gt?: number;
  gte?: number;
  in?: IntNullableWithAggregatesFilterIn;
  lt?: number;
  lte?: number;
  not?: IntNullableWithAggregatesFilterNot;
  notIn?: IntNullableWithAggregatesFilterNotIn;
}

export type BoolWithAggregatesFilterNot = boolean | NestedBoolWithAggregatesFilter;

export interface BoolWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedBoolFilter;
  _min?: NestedBoolFilter;
  equals?: boolean;
  not?: BoolWithAggregatesFilterNot;
}

export type StringNullableWithAggregatesFilterNotIn = string[] | string | null;

export type StringNullableWithAggregatesFilterNot = string | NestedStringNullableWithAggregatesFilter | null;

export type StringNullableWithAggregatesFilterIn = string[] | string | null;

export type StringNullableWithAggregatesFilterEquals = null | string;

export interface StringNullableWithAggregatesFilter {
  _count?: NestedIntNullableFilter;
  _max?: NestedStringNullableFilter;
  _min?: NestedStringNullableFilter;
  contains?: string;
  endsWith?: string;
  equals?: StringNullableWithAggregatesFilterEquals;
  gt?: string;
  gte?: string;
  in?: StringNullableWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: StringNullableWithAggregatesFilterNot;
  notIn?: StringNullableWithAggregatesFilterNotIn;
  startsWith?: string;
}

export type DateTimeWithAggregatesFilterNotIn = string[] | string;

export type DateTimeWithAggregatesFilterNot = string | NestedDateTimeWithAggregatesFilter;

export type DateTimeWithAggregatesFilterIn = string[] | string;

export interface DateTimeWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedDateTimeFilter;
  _min?: NestedDateTimeFilter;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: DateTimeWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: DateTimeWithAggregatesFilterNot;
  notIn?: DateTimeWithAggregatesFilterNotIn;
}

export interface SortOrderInput {
  nulls?: NullsOrder;
  sort: SortOrder;
}

export type UserRelationFilterIsNot = null | UserWhereInput;

export type UserRelationFilterIs = null | UserWhereInput;

export interface UserRelationFilter {
  is?: UserRelationFilterIs;
  isNot?: UserRelationFilterIsNot;
}

export type IntNullableFilterNotIn = number[] | number | null;

export type IntNullableFilterNot = number | NestedIntNullableFilter | null;

export type IntNullableFilterIn = number[] | number | null;

export type IntNullableFilterEquals = null | number;

export interface IntNullableFilter {
  equals?: IntNullableFilterEquals;
  gt?: number;
  gte?: number;
  in?: IntNullableFilterIn;
  lt?: number;
  lte?: number;
  not?: IntNullableFilterNot;
  notIn?: IntNullableFilterNotIn;
}

export type BoolFilterNot = boolean | NestedBoolFilter;

export interface BoolFilter {
  equals?: boolean;
  not?: BoolFilterNot;
}

export type StringNullableFilterNotIn = string[] | string | null;

export type StringNullableFilterNot = string | NestedStringNullableFilter | null;

export type StringNullableFilterIn = string[] | string | null;

export type StringNullableFilterEquals = null | string;

export interface StringNullableFilter {
  contains?: string;
  endsWith?: string;
  equals?: StringNullableFilterEquals;
  gt?: string;
  gte?: string;
  in?: StringNullableFilterIn;
  lt?: string;
  lte?: string;
  not?: StringNullableFilterNot;
  notIn?: StringNullableFilterNotIn;
  startsWith?: string;
}

export type DateTimeFilterNotIn = string[] | string;

export type DateTimeFilterNot = string | NestedDateTimeFilter;

export type DateTimeFilterIn = string[] | string;

export interface DateTimeFilter {
  equals?: string;
  gt?: string;
  gte?: string;
  in?: DateTimeFilterIn;
  lt?: string;
  lte?: string;
  not?: DateTimeFilterNot;
  notIn?: DateTimeFilterNotIn;
}

export type StringWithAggregatesFilterNotIn = string[] | string;

export type StringWithAggregatesFilterNot = string | NestedStringWithAggregatesFilter;

export type StringWithAggregatesFilterIn = string[] | string;

export interface StringWithAggregatesFilter {
  _count?: NestedIntFilter;
  _max?: NestedStringFilter;
  _min?: NestedStringFilter;
  contains?: string;
  endsWith?: string;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: StringWithAggregatesFilterIn;
  lt?: string;
  lte?: string;
  not?: StringWithAggregatesFilterNot;
  notIn?: StringWithAggregatesFilterNotIn;
  startsWith?: string;
}

export type IntWithAggregatesFilterNotIn = number[] | number;

export type IntWithAggregatesFilterNot = number | NestedIntWithAggregatesFilter;

export type IntWithAggregatesFilterIn = number[] | number;

export interface IntWithAggregatesFilter {
  _avg?: NestedFloatFilter;
  _count?: NestedIntFilter;
  _max?: NestedIntFilter;
  _min?: NestedIntFilter;
  _sum?: NestedIntFilter;
  equals?: number;
  gt?: number;
  gte?: number;
  in?: IntWithAggregatesFilterIn;
  lt?: number;
  lte?: number;
  not?: IntWithAggregatesFilterNot;
  notIn?: IntWithAggregatesFilterNotIn;
}

export interface PostOrderByRelationAggregateInput {
  _count?: SortOrder;
}

export interface PostListRelationFilter {
  every?: PostWhereInput;
  none?: PostWhereInput;
  some?: PostWhereInput;
}

export type StringFilterNotIn = string[] | string;

export type StringFilterNot = string | NestedStringFilter;

export type StringFilterIn = string[] | string;

export interface StringFilter {
  contains?: string;
  endsWith?: string;
  equals?: string;
  gt?: string;
  gte?: string;
  in?: StringFilterIn;
  lt?: string;
  lte?: string;
  not?: StringFilterNot;
  notIn?: StringFilterNotIn;
  startsWith?: string;
}

export type IntFilterNotIn = number[] | number;

export type IntFilterNot = number | NestedIntFilter;

export type IntFilterIn = number[] | number;

export interface IntFilter {
  equals?: number;
  gt?: number;
  gte?: number;
  in?: IntFilterIn;
  lt?: number;
  lte?: number;
  not?: IntFilterNot;
  notIn?: IntFilterNotIn;
}

export type PostUpdateManyMutationInputViewCount = number | IntFieldUpdateOperationsInput;

export type PostUpdateManyMutationInputUpdatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateManyMutationInputTitle = string | StringFieldUpdateOperationsInput;

export type PostUpdateManyMutationInputPublished = boolean | BoolFieldUpdateOperationsInput;

export type PostUpdateManyMutationInputCreatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateManyMutationInputContent = string | NullableStringFieldUpdateOperationsInput | null;

export interface PostUpdateManyMutationInput {
  content?: PostUpdateManyMutationInputContent;
  createdAt?: PostUpdateManyMutationInputCreatedAt;
  published?: PostUpdateManyMutationInputPublished;
  title?: PostUpdateManyMutationInputTitle;
  updatedAt?: PostUpdateManyMutationInputUpdatedAt;
  viewCount?: PostUpdateManyMutationInputViewCount;
}

export type PostUpdateInputViewCount = number | IntFieldUpdateOperationsInput;

export type PostUpdateInputUpdatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateInputTitle = string | StringFieldUpdateOperationsInput;

export type PostUpdateInputPublished = boolean | BoolFieldUpdateOperationsInput;

export type PostUpdateInputCreatedAt = string | DateTimeFieldUpdateOperationsInput;

export type PostUpdateInputContent = string | NullableStringFieldUpdateOperationsInput | null;

export interface PostUpdateInput {
  author?: UserUpdateOneWithoutPostsNestedInput;
  content?: PostUpdateInputContent;
  createdAt?: PostUpdateInputCreatedAt;
  published?: PostUpdateInputPublished;
  title?: PostUpdateInputTitle;
  updatedAt?: PostUpdateInputUpdatedAt;
  viewCount?: PostUpdateInputViewCount;
}

export type PostCreateInputContent = null | string;

export interface PostCreateInput {
  author?: UserCreateNestedOneWithoutPostsInput;
  content?: PostCreateInputContent;
  createdAt?: string;
  published?: boolean;
  title: string;
  updatedAt?: string;
  viewCount?: number;
}

export type UserUpdateManyMutationInputName = string | StringFieldUpdateOperationsInput;

export type UserUpdateManyMutationInputEmail = string | StringFieldUpdateOperationsInput;

export interface UserUpdateManyMutationInput {
  email?: UserUpdateManyMutationInputEmail;
  name?: UserUpdateManyMutationInputName;
}

export type UserUpdateInputName = string | StringFieldUpdateOperationsInput;

export type UserUpdateInputEmail = string | StringFieldUpdateOperationsInput;

export interface UserUpdateInput {
  email?: UserUpdateInputEmail;
  name?: UserUpdateInputName;
  posts?: PostUpdateManyWithoutAuthorNestedInput;
}

export interface UserCreateInput {
  email: string;
  name: string;
  posts?: PostCreateNestedManyWithoutAuthorInput;
}

export type PostScalarWhereWithAggregatesInputViewCount = IntWithAggregatesFilter | number;

export type PostScalarWhereWithAggregatesInputUpdatedAt = DateTimeWithAggregatesFilter | string;

export type PostScalarWhereWithAggregatesInputTitle = StringWithAggregatesFilter | string;

export type PostScalarWhereWithAggregatesInputPublished = BoolWithAggregatesFilter | boolean;

export type PostScalarWhereWithAggregatesInputNOT = PostScalarWhereWithAggregatesInput | PostScalarWhereWithAggregatesInput[];

export type PostScalarWhereWithAggregatesInputId = IntWithAggregatesFilter | number;

export type PostScalarWhereWithAggregatesInputCreatedAt = DateTimeWithAggregatesFilter | string;

export type PostScalarWhereWithAggregatesInputContent = StringNullableWithAggregatesFilter | string | null;

export type PostScalarWhereWithAggregatesInputAuthorId = IntNullableWithAggregatesFilter | number | null;

export type PostScalarWhereWithAggregatesInputAND = PostScalarWhereWithAggregatesInput | PostScalarWhereWithAggregatesInput[];

export interface PostScalarWhereWithAggregatesInput {
  AND?: PostScalarWhereWithAggregatesInputAND;
  authorId?: PostScalarWhereWithAggregatesInputAuthorId;
  content?: PostScalarWhereWithAggregatesInputContent;
  createdAt?: PostScalarWhereWithAggregatesInputCreatedAt;
  id?: PostScalarWhereWithAggregatesInputId;
  NOT?: PostScalarWhereWithAggregatesInputNOT;
  OR?: PostScalarWhereWithAggregatesInput[];
  published?: PostScalarWhereWithAggregatesInputPublished;
  title?: PostScalarWhereWithAggregatesInputTitle;
  updatedAt?: PostScalarWhereWithAggregatesInputUpdatedAt;
  viewCount?: PostScalarWhereWithAggregatesInputViewCount;
}

export type PostWhereUniqueInputViewCount = IntFilter | number;

export type PostWhereUniqueInputUpdatedAt = DateTimeFilter | string;

export type PostWhereUniqueInputTitle = StringFilter | string;

export type PostWhereUniqueInputPublished = BoolFilter | boolean;

export type PostWhereUniqueInputNOT = PostWhereInput | PostWhereInput[];

export type PostWhereUniqueInputCreatedAt = DateTimeFilter | string;

export type PostWhereUniqueInputContent = StringNullableFilter | string | null;

export type PostWhereUniqueInputAuthorId = IntNullableFilter | number | null;

export type PostWhereUniqueInputAuthor = UserRelationFilter | UserWhereInput | null;

export type PostWhereUniqueInputAND = PostWhereInput | PostWhereInput[];

export interface PostWhereUniqueInput {
  AND?: PostWhereUniqueInputAND;
  author?: PostWhereUniqueInputAuthor;
  authorId?: PostWhereUniqueInputAuthorId;
  content?: PostWhereUniqueInputContent;
  createdAt?: PostWhereUniqueInputCreatedAt;
  id?: number;
  NOT?: PostWhereUniqueInputNOT;
  OR?: PostWhereInput[];
  published?: PostWhereUniqueInputPublished;
  title?: PostWhereUniqueInputTitle;
  updatedAt?: PostWhereUniqueInputUpdatedAt;
  viewCount?: PostWhereUniqueInputViewCount;
}

export type PostOrderByWithRelationInputContent = SortOrder | SortOrderInput;

export type PostOrderByWithRelationInputAuthorId = SortOrder | SortOrderInput;

export interface PostOrderByWithRelationInput {
  author?: UserOrderByWithRelationInput;
  authorId?: PostOrderByWithRelationInputAuthorId;
  content?: PostOrderByWithRelationInputContent;
  createdAt?: SortOrder;
  id?: SortOrder;
  published?: SortOrder;
  title?: SortOrder;
  updatedAt?: SortOrder;
  viewCount?: SortOrder;
}

export type PostWhereInputViewCount = IntFilter | number;

export type PostWhereInputUpdatedAt = DateTimeFilter | string;

export type PostWhereInputTitle = StringFilter | string;

export type PostWhereInputPublished = BoolFilter | boolean;

export type PostWhereInputNOT = PostWhereInput | PostWhereInput[];

export type PostWhereInputId = IntFilter | number;

export type PostWhereInputCreatedAt = DateTimeFilter | string;

export type PostWhereInputContent = StringNullableFilter | string | null;

export type PostWhereInputAuthorId = IntNullableFilter | number | null;

export type PostWhereInputAuthor = UserRelationFilter | UserWhereInput | null;

export type PostWhereInputAND = PostWhereInput | PostWhereInput[];

export interface PostWhereInput {
  AND?: PostWhereInputAND;
  author?: PostWhereInputAuthor;
  authorId?: PostWhereInputAuthorId;
  content?: PostWhereInputContent;
  createdAt?: PostWhereInputCreatedAt;
  id?: PostWhereInputId;
  NOT?: PostWhereInputNOT;
  OR?: PostWhereInput[];
  published?: PostWhereInputPublished;
  title?: PostWhereInputTitle;
  updatedAt?: PostWhereInputUpdatedAt;
  viewCount?: PostWhereInputViewCount;
}

export type UserScalarWhereWithAggregatesInputNOT = UserScalarWhereWithAggregatesInput | UserScalarWhereWithAggregatesInput[];

export type UserScalarWhereWithAggregatesInputName = StringWithAggregatesFilter | string;

export type UserScalarWhereWithAggregatesInputId = IntWithAggregatesFilter | number;

export type UserScalarWhereWithAggregatesInputEmail = StringWithAggregatesFilter | string;

export type UserScalarWhereWithAggregatesInputAND = UserScalarWhereWithAggregatesInput | UserScalarWhereWithAggregatesInput[];

export interface UserScalarWhereWithAggregatesInput {
  AND?: UserScalarWhereWithAggregatesInputAND;
  email?: UserScalarWhereWithAggregatesInputEmail;
  id?: UserScalarWhereWithAggregatesInputId;
  name?: UserScalarWhereWithAggregatesInputName;
  NOT?: UserScalarWhereWithAggregatesInputNOT;
  OR?: UserScalarWhereWithAggregatesInput[];
}

export type UserWhereUniqueInputNOT = UserWhereInput | UserWhereInput[];

export type UserWhereUniqueInputName = StringFilter | string;

export type UserWhereUniqueInputAND = UserWhereInput | UserWhereInput[];

export interface UserOrderByWithRelationInput {
  email?: SortOrder;
  id?: SortOrder;
  name?: SortOrder;
  posts?: PostOrderByRelationAggregateInput;
}

export type UserWhereInputNOT = UserWhereInput | UserWhereInput[];

export type UserWhereInputName = StringFilter | string;

export type UserWhereInputId = IntFilter | number;

export type UserWhereInputEmail = StringFilter | string;

export type UserWhereInputAND = UserWhereInput | UserWhereInput[];

export interface UserWhereInput {
  AND?: UserWhereInputAND;
  email?: UserWhereInputEmail;
  id?: UserWhereInputId;
  name?: UserWhereInputName;
  NOT?: UserWhereInputNOT;
  OR?: UserWhereInput[];
  posts?: PostListRelationFilter;
}

export interface UserWhereUniqueInput {
  AND?: UserWhereUniqueInputAND;
  email?: string;
  id?: number;
  name?: UserWhereUniqueInputName;
  NOT?: UserWhereUniqueInputNOT;
  OR?: UserWhereInput[];
  posts?: PostListRelationFilter;
}

export type PostContent = null | string;

export type PostAuthorId = null | number;

export interface Post {
  author?: PostAuthor;
  authorId?: PostAuthorId;
  content?: PostContent;
  createdAt: string;
  id: number;
  published: boolean;
  title: string;
  updatedAt: string;
  viewCount: number;
}

export interface User {
  email: string;
  id: number;
  name: string;
  posts?: Post[];
}

export type PostAuthor = null | User;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullsOrder = {
  first: "first",
  last: "last"
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOrder = {
  asc: "asc",
  desc: "desc"
} as const;

export type PostScalarFieldEnum = (typeof PostScalarFieldEnum)[keyof typeof PostScalarFieldEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostScalarFieldEnum = {
  id: "id",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  title: "title",
  content: "content",
  published: "published",
  viewCount: "viewCount",
  authorId: "authorId"
} as const;

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserScalarFieldEnum = {
  id: "id",
  email: "email",
  name: "name"
} as const;
